apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: balanceador
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx # Update the version of nginx from 1.14.2 to 1.16.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80