apiVersion: apps/v1 # kubectl create configmap --from-file 
kind: Deployment
metadata:
  name: produccion
spec: 
  selector:
    matchLabels: 
      app: nginx
  replicas: 2
  template: 
    metadata: 
      labels:
        app: nginx
    spec:
      containers: 
        - name: front-end
          image: nginx
          ports: 
            - containerPort: 80
          volumeMounts: 
            #- name: nginx-front-end
              #mountPath: /etc/nginx/conf.d
            - name: nginx-index
              mountPath: /usr/share/nginx/html
      volumes: 
        #- name: nginx-front-end
          #configMap: 
            #name: nginx-configuration
            #items: 
              #- key: nginx-default.conf
                #path: default.conf 
        - name: nginx-index
          configMap:
            name: nginx-configuration
            items: 
              - key: index.html
                path: index.html