apiVersion: v1 
kind: Service
metadata:
  name: balancer
  labels: 
    pp: my-nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector: 
    app: nginx
  type: LoadBalancer